# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PostSharp Blog
email: hello@postsharp.net
description: > # this means to ignore newlines until "baseurl:"
  Announcements, opinions, tips and tricks from PostSharp Technologies.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.postsharp.net" # the base hostname & protocol for your site
twitter_username: postsharp
github_username:  postsharp
facebook_username: postsharp
linkedin_username: postsharp

main_website_url: https://www.postsharp.net

title_separator: "|"

#excerpt_separator: "<!-- readmore -->"

plugins:
  - jekyll-feed
